export const SET_AUTH_USER_DATA = 'auth/SET_AUTH_USER_DATA';
export const AUTH_ERROR = 'auth/AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'auth/CLEAR_AUTH_ERROR';
export const AUTH_LOADING = 'auth/AUTH_LOADING';

export const SET_INITIALIZED = 'app/SET_INITIALIZED';

export const SET_TREATMENT_APPOINTMENTS_DATA = 'newAppointment/SET_TREATMENT_APPOINTMENTS_DATA';
export const NEW_APPOINTMENT_LOADING = 'newAppointment/NEW_APPOINTMENT_LOADING';